DROP TABLE IF EXISTS likes, users CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE likes (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER,
  game_id INTEGER,
  is_liked BOOLEAN
);

CREATE UNIQUE INDEX likes_user_id_game_id
ON likes (user_id, game_id);

ALTER USER reviewr WITH SUPERUSER;
GRANT ALL PRIVILEGES ON DATABASE reviewrdb TO reviewr;
GRANT ALL PRIVILEGES ON TABLE likes TO reviewr
