CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  username VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE game (
  id SERIAL PRIMARY KEY NOT NULL,
  thumbnail_url VARCHAR(2048),
  cover_url VARCHAR(2048),
  name VARCHAR(255) NOT NULL,
  genre VARCHAR
)